name: app_dog_images
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-248.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  bloc: ^8.0.0
  freezed_annotation: ^2.2.0
  cached_network_image: ^3.2.0
  path_provider: ^2.0.11
  shared_preferences: ^2.1.0
  json_annotation: ^4.7.0
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  freezed: ^2.2.0
  json_serializable: ^6.1.6


flutter:
  uses-material-design: true
